services:
    _defaults:
        autoconfigure: true
        public: false

    BugBuster\BannerBundle\Controller\BannerFeController:
        public: true
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

    BugBuster\BannerBundle\Migration\Version120Update:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
