services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BugBuster\BannerBundle\Controller\BannerFeController:
        public: true
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

    BugBuster\BannerBundle\Migration\Version120Update:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    # bug_buster_banner.logger:
    #     class: "BugBuster\\BannerBundle\\Classes\\BannerLogger"
    BugBuster\BannerBundle\Classes\BannerLogger:
        public: true
        arguments: 
            - '@service_container'
            - '@logger'
            - '@monolog.logger.contao'
        tags:
            - 
                name: monolog.logger
                channel: banner

    bug_buster_banner.logger:
        alias: BugBuster\BannerBundle\Classes\BannerLogger
        public: true
